/// Stress tests with large strings and dictionaries.
///
/// These tests are excluded from the default test suite (they are skipped
/// unless the `STRESS` dart-define is set). Run them with:
///
/// ```sh
/// flutter test --dart-define=STRESS=true test/stress/stress_test.dart \
///   --reporter expanded
/// ```
///
/// Everything is deterministic (fixed RNG seeds), so runs are reproducible
/// and results comparable across versions.
library;

import 'dart:io';
import 'dart:math';

import 'package:flutter/foundation.dart';

import 'package:flutter_test/flutter_test.dart';
import 'package:novident_spell_checker/novident_spell_checker.dart';

import '../dictionary_test.dart' show FakeAssetBundle;

const bool _runStress = bool.fromEnvironment('STRESS', defaultValue: false);

const String _skipReason = 'Stress tests: run with --dart-define=STRESS=true';

/// Deterministic synthetic corpus generator.
class _Generator {
  _Generator(this.rng);

  final Random rng;

  static const String _consonants = 'bcdfghjklmnprstvz';
  static const String _vowels = 'aeiou';
  static const String _letters = 'abcdefghijklmnopqrstuvwxyz';

  /// Random word of length [length] (consonant/vowel alternation).
  String wordOfLength(int length) {
    final sb = StringBuffer();
    for (var i = 0; i < length; i++) {
      final source = i.isEven ? _consonants : _vowels;
      sb.write(source[rng.nextInt(source.length)]);
    }
    return sb.toString();
  }

  /// Random word of length 5..[maxLength].
  String word([int maxLength = 12]) =>
      wordOfLength(5 + rng.nextInt(maxLength - 4));

  /// [count] unique random words of length 5..[maxLength].
  Set<String> words(int count, {int maxLength = 12}) {
    final set = <String>{};
    while (set.length < count) {
      set.add(word(maxLength));
    }
    return set;
  }

  /// Vocabulary of [count] words that are pairwise at edit distance >= 3,
  /// so distance-1 typos are unambiguous (by triangle inequality).
  Set<String> vocab(int count, [int maxLength = 12]) {
    final editDistance = DamerauLevenshteinDistance();
    final accepted = <String>{};
    while (accepted.length < count) {
      final candidate = word(maxLength);
      final tooClose = accepted.any(
        (w) => editDistance.calculateDistance(w, candidate) < 3,
      );
      if (!tooClose) {
        accepted.add(candidate);
      }
    }
    return accepted;
  }

  /// Replaces a single random char of [w] with a different one.
  String misspell(String w) {
    final pos = rng.nextInt(w.length);
    final original = w[pos];
    var replacement = original;
    while (replacement == original) {
      replacement = _letters[rng.nextInt(_letters.length)];
    }
    return w.substring(0, pos) + replacement + w.substring(pos + 1);
  }
}

void main() {
  final skip = _runStress ? false : _skipReason;

  group('Stress: large dictionaries', () {
    test('trains 20k terms and keeps lookups correct', skip: skip, () {
      final generator = _Generator(Random(42));
      final symSpell = SymSpellEx(MemoryStore())..initialize();

      // Controlled vocabulary (pairwise distance >= 3) for unambiguous
      // assertions regardless of the bulk dictionary contents.
      final controlled = generator.vocab(30);
      final probe = controlled.first;
      final bulk = generator.words(20000);

      final stopwatch = Stopwatch()..start();
      for (final term in controlled) {
        symSpell.add(term, 10);
      }
      var i = 0;
      for (final term in bulk) {
        symSpell.add(term, 1 + (i++ % 100));
      }
      stopwatch.stop();

      debugPrint(
        '[STRESS] train 20,030 terms: '
        '${stopwatch.elapsedMilliseconds} ms',
      );

      expect(stopwatch.elapsed, lessThan(const Duration(minutes: 2)));

      // Exact term lookup is unambiguous regardless of dictionary size.
      final exact = symSpell.lookup(probe);
      expect(exact, isNotEmpty);
      expect(exact.first.suggestion, probe);
      expect(exact.first.distance, 0);
    });
  });

  group('Stress: long words', () {
    test('adds and corrects a 200-char word (maxDistance 2)', skip: skip, () {
      final generator = _Generator(Random(7));
      final symSpell = SymSpellEx(MemoryStore())..initialize();
      final longWord = generator.wordOfLength(200);

      final addStopwatch = Stopwatch()..start();
      symSpell.add(longWord, 10);
      addStopwatch.stop();

      final typo = generator.misspell(longWord);

      final lookupStopwatch = Stopwatch()..start();
      final suggestions = symSpell.lookup(typo);
      lookupStopwatch.stop();

      // ~C(200,1) + C(200,2) = 20,100 delete keys generated by add().
      debugPrint(
        '[STRESS] add 200-char word (~20,100 delete keys): '
        '${addStopwatch.elapsedMilliseconds} ms',
      );
      debugPrint(
        '[STRESS] lookup 200-char typo: '
        '${lookupStopwatch.elapsedMilliseconds} ms',
      );

      expect(addStopwatch.elapsed, lessThan(const Duration(seconds: 30)));
      expect(lookupStopwatch.elapsed, lessThan(const Duration(seconds: 30)));
      expect(suggestions, isNotEmpty);
      expect(suggestions.first.suggestion, longWord);
      expect(suggestions.first.distance, 1);

      // Full-string correction of the long word itself.
      final correction = symSpell.correct(longWord, Languages.english);
      expect(correction!.output, longWord);
    });

    test('adds and corrects a 40-char word (maxDistance 3)', skip: skip, () {
      final generator = _Generator(Random(7));
      final symSpell = SymSpellEx(MemoryStore())..initialize();
      final word40 = generator.wordOfLength(40);

      final stopwatch = Stopwatch()..start();
      // ~C(40,1) + C(40,2) + C(40,3) = 10,700 delete keys.
      symSpell.add(word40, 10, Languages.english, 3);
      stopwatch.stop();
      debugPrint(
        '[STRESS] add 40-char word (maxDistance 3, ~10,700 delete keys): '
        '${stopwatch.elapsedMilliseconds} ms',
      );

      expect(stopwatch.elapsed, lessThan(const Duration(seconds: 30)));

      final typo = generator.misspell(word40);
      final suggestions = symSpell.lookup(typo, maxDistance: 3);

      expect(suggestions, isNotEmpty);
      expect(suggestions.first.suggestion, word40);
      expect(suggestions.first.distance, 1);
    });
  });

  group('Stress: huge sentences', () {
    test('corrects 1k and 10k word sentences', skip: skip, () {
      final generator = _Generator(Random(1234));
      final vocab = generator.vocab(30).toList();
      final symSpell = SymSpellEx(MemoryStore())..initialize();
      for (final term in vocab) {
        symSpell.add(term, 5);
      }

      for (final wordCount in const [1000, 10000]) {
        final cleanWords = List<String>.generate(
          wordCount,
          (_) => vocab[generator.rng.nextInt(vocab.length)],
        );
        final typoCount = wordCount * 5 ~/ 100;
        final typoPositions = <int>{};
        while (typoPositions.length < typoCount) {
          typoPositions.add(generator.rng.nextInt(wordCount));
        }

        final inputWords = List<String>.of(cleanWords);
        for (final pos in typoPositions) {
          inputWords[pos] = generator.misspell(cleanWords[pos]);
        }

        final input = inputWords.join(' ');
        final expected = cleanWords.join(' ');

        final stopwatch = Stopwatch()..start();
        final correction = symSpell.correct(input, Languages.english);
        stopwatch.stop();

        final kb = (input.length / 1000).toStringAsFixed(1);
        debugPrint(
          '[STRESS] correct($wordCount words / $kb KB, $typoCount typos): '
          '${stopwatch.elapsedMilliseconds} ms',
        );

        expect(stopwatch.elapsed, lessThan(const Duration(minutes: 1)));
        expect(correction, isNotNull);
        expect(correction!.output, expected);
        expect(
          correction.suggestions.where((s) => s.distance > 0).length,
          typoCount,
        );
      }
    });
  });

  group('Stress: vocabulary structures (symspell vs set vs trie)', () {
    test('compares build and exact lookup of 20k words', skip: skip, () {
      final generator = _Generator(Random(11));
      final words = generator.words(20000).toList();

      // 1. SymSpell symmetric delete index (supports fuzzy suggestions).
      final symSpell = SymSpellEx(MemoryStore())..initialize();
      var stopwatch = Stopwatch()..start();
      for (final w in words) {
        symSpell.add(w, 1);
      }
      stopwatch.stop();
      final trainMs = stopwatch.elapsedMilliseconds;
      final store = symSpell.store as MemoryStore;
      final entryCount = store.entryCount;

      // 2. HashSet (exact membership only).
      stopwatch = Stopwatch()..start();
      final wordSet = <String>{};
      for (final w in words) {
        wordSet.add(w);
      }
      stopwatch.stop();
      final setBuildMs = stopwatch.elapsedMilliseconds;

      // 3. Trie (exact membership + prefix queries).
      stopwatch = Stopwatch()..start();
      final trie = Trie.fromLines(words);
      stopwatch.stop();
      final trieBuildMs = stopwatch.elapsedMilliseconds;
      final nodeCount = trie.nodeCount;

      debugPrint(
        '[STRESS] build 20k words: symspell $trainMs ms '
        '($entryCount entries) | set $setBuildMs ms | '
        'trie $trieBuildMs ms ($nodeCount nodes)',
      );

      expect(trainMs, greaterThan(0));
      expect(symSpell.store.maxEntryLength(), greaterThan(0));

      // Exact membership probes: half known, half unknown.
      final probes = List<String>.generate(50000, (i) {
        final w = words[generator.rng.nextInt(words.length)];
        return i.isEven ? w : '${w}x';
      });

      stopwatch = Stopwatch()..start();
      var symspellHits = 0;
      for (final p in probes) {
        if (symSpell.hasTerm(p)) {
          symspellHits++;
        }
      }
      stopwatch.stop();
      final hasTermMs = stopwatch.elapsedMilliseconds;

      stopwatch = Stopwatch()..start();
      var setHits = 0;
      for (final p in probes) {
        if (wordSet.contains(p)) {
          setHits++;
        }
      }
      stopwatch.stop();
      final setMs = stopwatch.elapsedMilliseconds;

      stopwatch = Stopwatch()..start();
      var trieHits = 0;
      for (final p in probes) {
        if (trie.contains(p)) {
          trieHits++;
        }
      }
      stopwatch.stop();
      final trieMs = stopwatch.elapsedMilliseconds;

      debugPrint(
        '[STRESS] 50k exact probes: hasTerm $hasTermMs ms | '
        'set.contains $setMs ms | trie.contains $trieMs ms '
        '(hits: $symspellHits/$setHits/$trieHits)',
      );

      // Memory proxy: delete index entries vs trie nodes vs raw words.
      debugPrint(
        '[STRESS] memory proxy: $entryCount entries vs '
        '$nodeCount trie nodes vs ${words.length} words '
        '(${(entryCount / words.length).toStringAsFixed(1)}x / '
        '${(nodeCount / words.length).toStringAsFixed(1)}x)',
      );

      // All three structures must agree on the same vocabulary.
      expect(symspellHits, setHits);
      expect(setHits, trieHits);
      expect(setHits, greaterThanOrEqualTo(25000)); // at least the known half
    });
  });

  group('Stress: throughput', () {
    test('lookup throughput over a 5k dictionary', skip: skip, () {
      final generator = _Generator(Random(9));
      final symSpell = SymSpellEx(MemoryStore())..initialize();
      final dict = generator.words(5000).toList();
      for (final term in dict) {
        symSpell.add(term, 1);
      }

      final typos = List<String>.generate(
        2000,
        (_) => generator.misspell(dict[generator.rng.nextInt(dict.length)]),
      );

      final stopwatch = Stopwatch()..start();
      var found = 0;
      for (final typo in typos) {
        if (symSpell.lookup(typo).isNotEmpty) {
          found++;
        }
      }
      stopwatch.stop();

      final ms = stopwatch.elapsedMilliseconds;
      final opsPerSec = ms == 0 ? 0.0 : typos.length * 1000 / ms;
      debugPrint(
        '[STRESS] 2,000 lookups over 5k dictionary: $ms ms '
        '($found found, ${opsPerSec.toStringAsFixed(0)} lookups/sec)',
      );

      expect(found, typos.length);
      expect(stopwatch.elapsed, lessThan(const Duration(seconds: 60)));
    });
  });

  group('Stress: memory hygiene', () {
    test('clear() resets after heavy training', skip: skip, () {
      final generator = _Generator(Random(3));
      final symSpell = SymSpellEx(MemoryStore())..initialize();
      final dict = generator.words(10000).toList();
      for (final term in dict) {
        symSpell.add(term, 1);
      }
      final probe = dict.first;

      expect(symSpell.lookup(probe), isNotEmpty);

      symSpell.clear();
      expect(symSpell.lookup(probe), isEmpty);

      // Store remains fully usable after clear.
      symSpell.add(probe, 1);
      expect(symSpell.lookup(probe), isNotEmpty);
    });
  });

  group('Stress: Hunspell dictionary pipeline', () {
    const hunspellAsset = 'test/assets/dictionaries/es_ES.dic';

    test('parses a real 58k-word .dic file', skip: skip, () {
      final stopwatch = Stopwatch()..start();
      final dict = HunspellDictionary.fromLines(
        File(hunspellAsset).readAsLinesSync(),
      );
      stopwatch.stop();

      debugPrint(
        '[STRESS] parse es_ES.dic (58,221 lines / 700 KB): '
        '${stopwatch.elapsedMilliseconds} ms '
        '(${dict.length} terms, ${dict.flags.length} flagged, '
        '${dict.pairs.length} pairs, ${dict.forbidden.length} forbidden)',
      );

      expect(dict.length, greaterThan(50000));
      expect(dict.flags, isNotEmpty);
      expect(stopwatch.elapsed, lessThan(const Duration(seconds: 30)));
    });

    test(
      'trains and queries a Hunspell dictionary',
      timeout: const Timeout(Duration(minutes: 3)),
      skip: skip,
      () {
        final dict = HunspellDictionary.fromLines(
          File(hunspellAsset).readAsLinesSync(),
        );

        final symSpell = SymSpellEx(MemoryStore())..initialize();
        final stopwatch = Stopwatch()..start();
        symSpell.trainDictionary(dict.terms, Languages.spanish);
        stopwatch.stop();
        final store = symSpell.store as MemoryStore;

        debugPrint(
          '[STRESS] train es_ES (${dict.length} terms): '
          '${stopwatch.elapsedMilliseconds} ms '
          '(${store.entryCount} entries, '
          '${(store.entryCount / dict.length).toStringAsFixed(1)}x '
          'amplification)',
        );

        expect(stopwatch.elapsed, lessThan(const Duration(minutes: 2)));

        // Recall throughput on substitution typos of real dictionary words.
        final generator = _Generator(Random(21));
        final words = dict.terms.terms.keys
            .where((w) => w.length >= 6)
            .toList();
        final typos = List<(String, String)>.generate(5000, (_) {
          final word = words[generator.rng.nextInt(words.length)];
          return (word, generator.misspell(word));
        });

        final lookupStopwatch = Stopwatch()..start();
        var recalled = 0;
        for (final (word, typo) in typos) {
          final suggestions = symSpell.lookup(
            typo,
            language: Languages.spanish,
            maxSuggestions: 50,
          );
          if (suggestions.any((s) => s.suggestion == word)) {
            recalled++;
          }
        }
        lookupStopwatch.stop();

        final ms = lookupStopwatch.elapsedMilliseconds;
        final opsPerSec = ms == 0 ? 0.0 : typos.length * 1000 / ms;
        final recallRate = 100 * recalled / typos.length;
        debugPrint(
          '[STRESS] 5,000 typo lookups on es_ES: $ms ms '
          '(${opsPerSec.toStringAsFixed(0)} lookups/sec, '
          'recall ${recallRate.toStringAsFixed(1)}%)',
        );

        expect(recalled, greaterThanOrEqualTo(typos.length * 97 ~/ 100));
        expect(lookupStopwatch.elapsed, lessThan(const Duration(seconds: 60)));
      },
    );

    test(
      'loadHunspell asset loader parses a large dictionary',
      skip: skip,
      () async {
        final content = File(hunspellAsset).readAsStringSync();
        final bundle = FakeAssetBundle({'assets/es_ES.dic': content});

        final stopwatch = Stopwatch()..start();
        final dict = await AssetDictionaryLoader.loadHunspell(
          'assets/es_ES.dic',
          bundle: bundle,
        );
        stopwatch.stop();

        debugPrint(
          '[STRESS] loadHunspell (700 KB asset): '
          '${stopwatch.elapsedMilliseconds} ms (${dict.length} terms)',
        );

        expect(dict.length, greaterThan(50000));
        expect(stopwatch.elapsed, lessThan(const Duration(seconds: 30)));
      },
    );
  });

  group('Stress: streaming I/O', () {
    test(
      'trains and exports 60k lines through streams',
      timeout: const Timeout(Duration(minutes: 3)),
      skip: skip,
      () async {
        final generator = _Generator(Random(31));
        final lines = generator.words(60000).map((w) {
          return '$w,${1 + generator.rng.nextInt(100)}';
        }).toList();

        final symSpell = SymSpellEx(MemoryStore())..initialize();

        final trainWatch = Stopwatch()..start();
        await symSpell.trainLineStream(Stream.fromIterable(lines));
        trainWatch.stop();

        final dir = Directory.systemTemp.createTempSync('spell_stream_');
        addTearDown(() => dir.deleteSync(recursive: true));
        final file = File('${dir.path}/exported.txt');

        final exportWatch = Stopwatch()..start();
        await symSpell.exportStream().pipe(file.openWrite());
        exportWatch.stop();

        final sizeMb = (file.lengthSync() / (1024 * 1024)).toStringAsFixed(1);
        debugPrint(
          '[STRESS] trainLineStream 60k lines: '
          '${trainWatch.elapsedMilliseconds} ms | exportStream: '
          '${exportWatch.elapsedMilliseconds} ms ($sizeMb MB written)',
        );

        expect(file.lengthSync(), greaterThan(500 * 1024));
        expect(trainWatch.elapsed, lessThan(const Duration(minutes: 2)));
        expect(exportWatch.elapsed, lessThan(const Duration(minutes: 1)));

        // The streamed file reloads cleanly through chunked reads.
        final reloaded = await Dictionary.fromByteStream(
          file.openRead().map((c) => c),
        );
        expect(reloaded.length, 60000);
      },
    );
  });
}
