import 'dart:collection';

/// A single token produced by a [Tokenizer].
class Token {
  String value;
  String? tag;
  String? alphabet;
  int distance;

  Token(this.value, [this.tag, this.alphabet, this.distance = 0]);
}

/// A single correction suggestion for a term.
class Suggestion {
  String term;
  String? suggestion;
  int distance;
  int frequency;

  Suggestion(
    this.term,
    this.suggestion, [
    this.distance = 0,
    this.frequency = 0,
  ]);
}

/// The result of correcting a full input string.
class Correction {
  String input;
  String output;
  List<Suggestion> suggestions;

  Correction(this.input, this.output, [List<Suggestion>? suggestions])
    : suggestions = suggestions ?? <Suggestion>[];
}

/// Dictionary entry stored in a [DataStore].
///
/// Behaves like a [List] of integers where the first element is the term
/// frequency and any remaining elements are indexes of the terms this entry
/// suggests (used by delete-keys generated by the symmetric delete algorithm).
class DictionaryEntry extends ListBase<int> {
  // `int?` so growing via `length =` (ListBase.add) can null-fill slots
  // without a checked-mode cast error; slots are written right after growth.
  final List<int?> _values;

  DictionaryEntry([int frequency = 0, List<int> suggestions = const []])
    : _values = <int?>[frequency, ...suggestions];

  @override
  int get length => _values.length;

  @override
  set length(int newLength) => _values.length = newLength;

  @override
  int operator [](int index) => _values[index]!;

  @override
  void operator []=(int index, int value) => _values[index] = value;
}
